file = open("Sample_Data.csv",'a')
a = str(input("Enter the date(MM/DD/YYYY): "))
b = str(input("Enter your area: "))
c = str(input("Enter your name: "))
d = str(input("Enter item: "))
e = int(input("Enter Units: "))
f = int(input("Enter Unit Cost: "))
g = int(e * f)
e = str(e)
f = str(f)
g = str(g)
h = a + ',' + b + ',' + c + ',' + d + ',' + e + ',' + f + ',' + g
file.close()
file = open("Sample_Data.csv",'a')
file.write(h)
print('\n')
file.close()
file = open("Sample_Data.csv",'r')
print(file.read())
input("Press Enter to exit...")
file.close()
